### ISSUE TITLE
Work on unifying boss callbacks with BW and WA

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Unified#231]
Many weak auras specifically target only BW events like stage changes, timers, and announce.

In most cases, the WAs are compatible with DBM out of box if only they had also registered DBM callbacks. Unfortunately it's difficult to get authors to do this if they don't need to and end users don't often have skill to fix the WA packs they download.

The result, a large number of users are leaving DBM simply because fights "require" these weak auras.

The better solution would be if WA handled it smarter internally by simply smart combining the boss mod callbacks (especially for stage or timers using spellids and not timer id). Sadly, there doesn't seem to be much interest in this at the momen

Therefor, the more immediate solution seems to be to duplicate BWs callback handler in DBM and activate it by default if BW itself isn't installed (keyword installed, not loaded. strict check)

then sending all the BWs callbacks we're interesting in (announce, timer, stage, maybe others that weak auras use?). announce and timer would need additional filters to only pass it through handler if it's actually spellid passed, if it's not it might error due to different expectations of "timer id" field.

Links and more info:
https://twitter.com/deadlybossmods/status/1668842622234898433?s=61&t=qMqcrToMUKBCfbU6QB-uSQ
https://wago.io/LiquidAberrus
https://wago.io/rwUo_Neav
https://wago.io/Y2peTP20U

**Comment by MysticalOS** [comment]
Notes:

Fake callbacks need following points
1. BW_Stage needs to support using journal or total as return, changable per mod.
2. BW_Timer message text needs to auto strip "~" out of text before sending it, since BW puts ~ in timer itself and DBM inserts it in text (and that can cause text mismatch).
3. above all else, the check if BW is installed needs to be strict "is addon installed" not "is it loaded". cause we don't want to risk load order issues or load on demand stuff not being detected. DBM won't fake callbacks at all if BW is installed (even if it's disabled)

**Comment by MysticalOS** [comment]
Fake callback won't work. Most callbacks are compatible between DBM and bw, about only thing I see being an issue is just how inconsistent BW is with using staging compared to DBM.

----------------------------------------------------
Stage Change Notes

1. DBM tries to match Staging the journal outlines, so if a fight says bosses stages work like this: 1, 2, 1, 2, 3. then thats how DBM does it. BW tends to do 1 2 3 4 5 in that situation, but might also do 1 2 1 2 3. They're inconsistent.
2. DBM has a second arg it uses to do stage total. So even if DBM does do 1 2 1 2 3, it also passes 1 2 3 4 5 as second arg (total stage changes.
3. Likewise, DBM uses .5 for intermissions. So a fight might be 1, 1.5, 2, 2.5, and 3. Again, sometimes this is what BW does, but also sometimes they again just do 1 2 3 4 5.. Again DBM does both. Every time SetStage is called the second arg increments at 1 at a time to indicate total phase changes.

The basic conventions I'd like to see in both mods for stage changes:
1. SetStage/GetStage should really support both values in both mods and applied consistently. reason being it really makes sense for a weak aura. For example if a boss alternates 1 2 1 2. They might only care about x during the 2s and so they do their aura "and journal stage 2". but again they might also only care about second 2, so they'd use stage total 4. Sure with total they can go "stage total 2 and stage total 4" but thats less straight forward.
2. Intermissions should always be .5 , not just some of time depending on who wrote the module.

if BW doesn't want to do both journal and total, then both mods will just have to consistently just use stage total as an absolute and not be inconsistent. A WA dev just needs to know that stage n is stage n in both bw and DBM and that unified callback WAs adds will "just work".

----------------------------------------------------
Announce and timer object Notes

on my end, I'm probably just gonna have to make sure all timer/announce strings match whatever flavor text BW uses since some people foolishly use text triggers.

However, I do think both BW and DBM need to improve our timer and announce callbacks to send count. The reason some weak auras are scanning text is they are looking for "Bombs (1)" vs "(bombs 2)". current apis in both DBM and BW are lacking in this regard that if you try to search for timer or announce by spellid you can't go "spell Id but only count 2". This is a shortcoming both mods should address to help facilitate better written weak auras.

As for that spellid, we'll have to do a good job making sure we use the same spellid/option key in our objects so it's same. it's easy for it not to be same when multiple exist so it'll just mean touching base and applying consistency.

---------------------------

Summary
1. Get on same page with stage api, one way or another.
2. Improve callbacks of timer and announce objects to send count
3. Be on top of spellId and string matching of objects between BW and DBM

**Comment by MysticalOS** [comment]
Additional notes for WAs addon itself

As for field confusion in WA triggers themselves. "timer id" for dbm should be removed as a standard trigger in WA. That's a unique string (basically timer GUID) that's only needed for strictly advanced WAs like https://wago.io/RaidAbilityTimeline . it's not meant to be used for a standard general trigger and does indeed create confusion. for a general trigger it should only be usual stuff like text and spellId (and even text should be flagged "only if there isn't a spellid"

I'd like to also note this is why dbm has the "type" field with so many types. you can for example track a "phase" timer without a spellid and without localizing still by matching by type. It should be SUPER rare to ever need to localize a trigger

**Comment by MysticalOS** [comment]
Callbacks updated to include count per
https://github.com/DeadlyBossMods/DBM-Unified/commit/a9dae8eab96be1eb23b2001bd22710728ae5658a
and
https://github.com/DeadlyBossMods/DBM-Unified/commit/f6ff48031105194fb16a53a7c6d5ef94512a495d

This fixes primary reason WA devs had to scan message text at all. They should now be able to find count just checking spellId and count together.

**Comment by MysticalOS** [comment]
Upon review, BW doesn't follow conventions on which spellid to use for option key. DBM tries to always use the cast ID used by whatever event that starts the timer (with exception on if that id has a messed up/missing tooltip)

My review of bigwigs the last hour is there is no consistency, sometimes the option key is cast id sometimes it's debuff ID, likely it's just chosen with no unspecified convention as long as tooltip is fine, making it not possible for me to guess ahead of time what Id they'd use. I can't really blame them for not following a convention though. Mostly just making a note of it here that going forward I'm gonna have to review and update any drycodes/ptr mods I do and change my spellids to match to ensure WA compatibility. I'll make sure this gets done at same time as icon review when I do icon compatibility passes

**Comment by MysticalOS** [comment]
Delaying this push for couple days to maybe explore one more chance of doing it without breaking user settings or weak auras that already targeted DBM.

**Comment by Mitalie** [comment]
WeakAuras references BigWigs globals in three places:
1. `BigWigsLoader.RegisterMessage(addon, message, callback)` in `WeakAuras.RegisterBigWigsCallback`, to register for BigWigs callbacks in general.
2. `BigWigs:IterateBossModules()`, `module:IsEngaged()`, `module:GetStage()` in `WeakAuras.RegisterBigWigsCallback`, to sync BigWigs stage info in case of registering after the stage event has already fired.
3. `BigWigs:GetPlugin("Colors"):GetColorTable(type, mod, key)` in `bigWigsEventCallback`, to make colors from BigWigs available to custom code. This probably doesn't need to return anything meaningful, just a valid `{r, g, b}` table.

We could create the `BigWigs` and `BigWigsLoader` globals with appropriate functions, but the existence of those might confuse other addons into thinking BigWigs is loaded and calling other functions we did not create. To avoid this, we can instead use `setfenv` to give the WeakAuras functions a modified "global" environment where those are available. `bigWigsEventCallback` function is not directly reachable to us, but it is passed to `BigWigsLoader.RegisterMessage` so we can set its environment there.

---
The messages that WeakAuras registers and their arguments as used by WeakAuras are:
* `BigWigs_Message` `addon, key, text, _, icon`
* `BigWigs_StartBar` `addon, key, text, duration, icon, isCD`
* `BigWigs_StopBar` `_, text`
* `BigWigs_PauseBar` `_, text`
* `BigWigs_ResumeBar` `_, text`
* `BigWigs_StopBars` `addon`
* `BigWigs_OnBossDisable` `addon`
* `BigWigs_SetStage` `_, stage`

<br>

* `addon` is used to stop timers related to a particular mod. In `BigWigs_Message` `addon` is passed to trigger but currently unusable via trigger options as it is a table value; the trigger should probably check against `addon.moduleName` (bug in WeakAuras).
* `key`, usually spell ID and referred to as such in WA code, is what auras should primarily match; we will apply a mapping from DBM spellIds to BigWigs keys.
* `text` is the visible text, but also used as unique key for bars/timers - BigWigs itself won't display two bars with identical text, the old bar is always removed. Some auras match text instead of key; this should be discouraged in favor of key and count (number parsed out of text), but text in DBM can be changed on a case-by-case basis or a mapping can be applied.
* `duration` is self-explanatory.
* `icon` is not used for trigger checks, so probably doesn't need to match
* `isCD` corresponds to DBM's `~`-prefixed timers.
* `stage` needs either a per-mod mapping or a per-mod mode switch as discussed earlier in this thread.

`BigWigs_Message` and `BigWigs_SetStage` pass all arguments to custom triggers, but so far I've seen only the `stage` arg of `BigWigs_SetStage` used.

**Comment by MysticalOS** [comment]
[Liquid_-_Aberrus.txt](https://github.com/DeadlyBossMods/DBM-Unified/files/11948507/Liquid_-_Aberrus.txt)
[twins_Volcanic_Heart_Positions_1.txt](https://github.com/DeadlyBossMods/DBM-Unified/files/11948508/twins_Volcanic_Heart_Positions_1.txt)
[Volcanic_Heart_List__Map.txt](https://github.com/DeadlyBossMods/DBM-Unified/files/11948510/Volcanic_Heart_List__Map.txt)
[BDG_Angered_-_Neltharion_PortalHeart_Map.txt](https://github.com/DeadlyBossMods/DBM-Unified/files/11948512/BDG_Angered_-_Neltharion_PortalHeart_Map.txt)

Untested, but should be attached to ticket since users have been left with no solution yet.

**Comment by MysticalOS** [comment]
BTW, weak auras that were targetting DBM, should check the option key migration wiki here:
https://github.com/DeadlyBossMods/DBM-Retail/wiki/DBM-Option-Key-Migration-List

This outlines all the option key changes to ensure DBM matches BW for more compatible unified auras. If your aura relied on DBM having diff IDs from BWs, that's no longer the case in current alpha/next release.

**Comment by MysticalOS** [comment]
https://wago.io/21o-Hvmjh seems to work with DBM out of box as of few weeks ago, missed their fixes., so removing custom one from here
